/* 서드파티 블록 카탈로그 — scripts/gen-3p.mjs 가 생성한다. 직접 고치지 말 것.
 *
 * 공식 shadcn 이 다루지 않는 자리를 채운다 — 랜딩 · 마케팅 · 커머스 구획.
 * 종류마다 정의와 선택 조건을 쓰고, 각 항목이 그것을 물려받는다.
 * 전부 MIT 이며 출처는 항목마다 적혀 있다. */
import type { Copy } from "@/components/lang"

export type ThirdPartyBlock = {
  id: string
  source: "tailark" | "launch" | "space"
  kind: string
  variant: string
  what: Copy
  when: Copy
}

export const SOURCES: Record<string, { label: string; url: string; license: string }> = {
  tailark: { label: "Tailark", url: "https://github.com/tailark/blocks", license: "MIT" },
  launch: { label: "Launch UI", url: "https://github.com/launch-ui/launch-ui", license: "MIT" },
  space: { label: "Shadcn Space", url: "https://github.com/shadcnspace/shadcnspace", license: "MIT" },
}

export const THIRD_PARTY_BLOCKS: ThirdPartyBlock[] = [
  {
    id: "launch-cta",
    source: "launch",
    kind: "cta",
    variant: "cta",
    what: { ko: "페이지 끝에서 다음 행동 하나로 몰아준다.", en: "The closing push toward one action." },
    when: { ko: "선택지를 둘 이상 두지 않는다.", en: "Never more than one option." },
  },
  {
    id: "launch-faq",
    source: "launch",
    kind: "faq",
    variant: "faq",
    what: { ko: "반복되는 질문을 접어 둔 목록.", en: "Recurring questions, folded away." },
    when: { ko: "지원 문의가 같은 내용으로 계속 올 때.", en: "When support keeps getting the same question." },
  },
  {
    id: "launch-footer",
    source: "launch",
    kind: "footer",
    variant: "footer",
    what: { ko: "페이지 맨 아래의 링크 묶음.", en: "The link block at the bottom." },
    when: { ko: "법적 고지 · 연락처 · 부차 링크가 갈 곳. 여기 있는 것은 아무도 안 찾는다고 가정한다.", en: "Legal, contact, secondary links. Assume nobody goes looking here." },
  },
  {
    id: "launch-hero",
    source: "launch",
    kind: "hero",
    variant: "hero",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리.", en: "The first thing to settle on a landing page." },
  },
  {
    id: "launch-logos",
    source: "launch",
    kind: "logos",
    variant: "logos",
    what: { ko: "고객사 · 기술 스택 로고 묶음.", en: "A set of customer or stack logos." },
    when: { ko: "쓸 수 있는 로고가 충분할 때.", en: "When you have enough of them." },
  },
  {
    id: "launch-navbar",
    source: "launch",
    kind: "navbar",
    variant: "navbar",
    what: { ko: "최상단 전역 탐색.", en: "Global navigation at the top." },
    when: { ko: "링크가 두세 개면 그냥 나열한다. 하위 메뉴가 필요할 만큼 커졌을 때 쓴다.", en: "Two or three links? Just list them. This is for when submenus become necessary." },
  },
  {
    id: "launch-stats",
    source: "launch",
    kind: "stats",
    variant: "stats",
    what: { ko: "숫자 서너 개로 규모를 보인다.", en: "Three or four numbers showing scale." },
    when: { ko: "실제 숫자가 있을 때만. 없는 숫자를 지어내면 그 페이지 전체의 신뢰가 무너진다.", en: "Only with real numbers. Invented ones cost you the whole page's credibility." },
  },
  {
    id: "space-about-us-section-01",
    source: "space",
    kind: "about-us-section",
    variant: "about-us-section-01",
    what: { ko: "회사나 팀을 설명하는 구획.", en: "A section about the company." },
    when: { ko: "제품이 아니라 만드는 쪽을 물어보는 방문자가 있을 때.", en: "For visitors asking who's behind it, not what it does." },
  },
  {
    id: "space-bento-grid-01",
    source: "space",
    kind: "bento-grid",
    variant: "bento-grid-01",
    what: { ko: "크기가 다른 칸을 격자로 엮어 한눈에 훑게 한다.", en: "A grid of unequal cells scanned at once." },
    when: { ko: "항목의 중요도가 다를 때. 전부 같은 크기면 그냥 격자를 쓴다.", en: "When items differ in weight. If they're equal, use a plain grid." },
  },
  {
    id: "space-blog-01",
    source: "space",
    kind: "blog",
    variant: "blog-01",
    what: { ko: "글 목록.", en: "A list of posts." },
    when: { ko: "썸네일 · 제목 · 날짜 · 요약. 요약이 없으면 제목만으로 고르게 된다.", en: "Thumbnail, title, date, excerpt. Without the excerpt, only the title does the work." },
  },
  {
    id: "space-contact-01",
    source: "space",
    kind: "contact",
    variant: "contact-01",
    what: { ko: "연락 폼 또는 연락처.", en: "A contact form or details." },
    when: { ko: "제품이 아직 셀프서비스가 아닐 때. 응답 시간을 함께 적는다.", en: "When the product isn't self-serve yet. State the response time." },
  },
  {
    id: "space-cta-01",
    source: "space",
    kind: "cta",
    variant: "cta-01",
    what: { ko: "페이지 끝에서 다음 행동 하나로 몰아준다.", en: "The closing push toward one action." },
    when: { ko: "선택지를 둘 이상 두지 않는다.", en: "Never more than one option." },
  },
  {
    id: "space-empty-state-01",
    source: "space",
    kind: "empty-state",
    variant: "empty-state-01",
    what: { ko: "보여줄 것이 없을 때의 화면.", en: "The screen with nothing to show." },
    when: { ko: "우리 패턴 탭에도 5종이 있다. 마케팅 톤이 필요할 때만 이쪽.", en: "Our patterns tab has five. Use these only when a marketing tone is needed." },
  },
  {
    id: "space-faq-01",
    source: "space",
    kind: "faq",
    variant: "faq-01",
    what: { ko: "반복되는 질문을 접어 둔 목록.", en: "Recurring questions, folded away." },
    when: { ko: "지원 문의가 같은 내용으로 계속 올 때.", en: "When support keeps getting the same question." },
  },
  {
    id: "space-feature-01",
    source: "space",
    kind: "feature",
    variant: "feature-01",
    what: { ko: "제품이 무엇을 하는지 항목으로 나눠 보인다.", en: "What the product does, broken into items." },
    when: { ko: "히어로 바로 아래에 놓는다.", en: "Sits right under the hero." },
  },
  {
    id: "space-feature-02",
    source: "space",
    kind: "feature",
    variant: "feature-02",
    what: { ko: "제품이 무엇을 하는지 항목으로 나눠 보인다.", en: "What the product does, broken into items." },
    when: { ko: "히어로 바로 아래에 놓는다.", en: "Sits right under the hero." },
  },
  {
    id: "space-footer-01",
    source: "space",
    kind: "footer",
    variant: "footer-01",
    what: { ko: "페이지 맨 아래의 링크 묶음.", en: "The link block at the bottom." },
    when: { ko: "법적 고지 · 연락처 · 부차 링크가 갈 곳. 여기 있는 것은 아무도 안 찾는다고 가정한다.", en: "Legal, contact, secondary links. Assume nobody goes looking here." },
  },
  {
    id: "space-gallery-01",
    source: "space",
    kind: "gallery",
    variant: "gallery-01",
    what: { ko: "이미지 모음.", en: "A set of images." },
    when: { ko: "작업물이 곧 설득 재료인 경우 — 포트폴리오, 제품 사진.", en: "When the work itself is the argument — portfolios, product shots." },
  },
  {
    id: "space-hero-01",
    source: "space",
    kind: "hero",
    variant: "hero-01",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리.", en: "The first thing to settle on a landing page." },
  },
  {
    id: "space-hero-02",
    source: "space",
    kind: "hero",
    variant: "hero-02",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리.", en: "The first thing to settle on a landing page." },
  },
  {
    id: "space-hero-03",
    source: "space",
    kind: "hero",
    variant: "hero-03",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리.", en: "The first thing to settle on a landing page." },
  },
  {
    id: "space-logo-cloud-01",
    source: "space",
    kind: "logo-cloud",
    variant: "logo-cloud-01",
    what: { ko: "고객사 로고를 한 줄로.", en: "Customer logos in a row." },
    when: { ko: "쓸 수 있는 로고가 여섯 개 이상일 때. 세 개면 오히려 규모가 작아 보인다.", en: "Six or more. With three, it makes you look smaller." },
  },
  {
    id: "space-navbar-01",
    source: "space",
    kind: "navbar",
    variant: "navbar-01",
    what: { ko: "최상단 전역 탐색.", en: "Global navigation at the top." },
    when: { ko: "링크가 두세 개면 그냥 나열한다. 하위 메뉴가 필요할 만큼 커졌을 때 쓴다.", en: "Two or three links? Just list them. This is for when submenus become necessary." },
  },
  {
    id: "space-newsletter-01",
    source: "space",
    kind: "newsletter",
    variant: "newsletter-01",
    what: { ko: "메일 구독 받기.", en: "Email capture." },
    when: { ko: "지금 살 준비는 안 됐지만 관심 있는 사람을 잡을 때.", en: "For people interested but not ready to buy." },
  },
  {
    id: "space-pricing-01",
    source: "space",
    kind: "pricing",
    variant: "pricing-01",
    what: { ko: "요금제를 나란히 놓고 고르게 하는 표.", en: "Plans side by side." },
    when: { ko: "안이 3개를 넘으면 비교가 안 된다. 그 이상이면 비교표(comparator)로 바꾼다.", en: "Past three tiers, comparison stops working — switch to a comparator." },
  },
  {
    id: "space-pricing-02",
    source: "space",
    kind: "pricing",
    variant: "pricing-02",
    what: { ko: "요금제를 나란히 놓고 고르게 하는 표.", en: "Plans side by side." },
    when: { ko: "안이 3개를 넘으면 비교가 안 된다. 그 이상이면 비교표(comparator)로 바꾼다.", en: "Past three tiers, comparison stops working — switch to a comparator." },
  },
  {
    id: "space-services-01",
    source: "space",
    kind: "services",
    variant: "services-01",
    what: { ko: "제공하는 일을 항목으로 나눈다.", en: "What you do, itemized." },
    when: { ko: "제품이 아니라 용역을 파는 경우.", en: "When you sell service rather than product." },
  },
  {
    id: "space-statistics-01",
    source: "space",
    kind: "statistics",
    variant: "statistics-01",
    what: { ko: "숫자 서너 개로 규모를 보인다.", en: "Three or four numbers showing scale." },
    when: { ko: "실제 숫자가 있을 때만 쓴다.", en: "Only with real numbers." },
  },
  {
    id: "space-team-01",
    source: "space",
    kind: "team",
    variant: "team-01",
    what: { ko: "만드는 사람들을 보인다.", en: "The people behind it." },
    when: { ko: "사람이 곧 신뢰인 업종 — 에이전시, 컨설팅, 의료.", en: "Where people are the trust — agencies, consulting, care." },
  },
  {
    id: "space-testimonial-01",
    source: "space",
    kind: "testimonial",
    variant: "testimonial-01",
    what: { ko: "쓴 사람의 말을 인용한다.", en: "Quotes from people who used it." },
    when: { ko: "실명과 소속이 없으면 효과가 없다.", en: "Without a real name and org, it does nothing." },
  },
  {
    id: "tailark-dusk-call-to-action-one",
    source: "tailark",
    kind: "call-to-action",
    variant: "dusk · one",
    what: { ko: "페이지 끝에서 다음 행동 하나로 몰아준다.", en: "The closing push toward one action." },
    when: { ko: "스크롤을 끝까지 내린 사람에게 마지막으로 묻는 자리. 선택지를 둘 이상 두지 않는다.", en: "The last ask for someone who scrolled all the way. Never more than one option." },
  },
  {
    id: "tailark-dusk-call-to-action-two",
    source: "tailark",
    kind: "call-to-action",
    variant: "dusk · two",
    what: { ko: "페이지 끝에서 다음 행동 하나로 몰아준다.", en: "The closing push toward one action." },
    when: { ko: "스크롤을 끝까지 내린 사람에게 마지막으로 묻는 자리. 선택지를 둘 이상 두지 않는다.", en: "The last ask for someone who scrolled all the way. Never more than one option." },
  },
  {
    id: "tailark-dusk-content-four",
    source: "tailark",
    kind: "content",
    variant: "dusk · four",
    what: { ko: "글과 이미지가 섞인 설명 구획.", en: "A prose-and-image section." },
    when: { ko: "히어로에서 다 못한 이야기를 이어갈 때.", en: "For continuing what the hero couldn't finish." },
  },
  {
    id: "tailark-dusk-content-one",
    source: "tailark",
    kind: "content",
    variant: "dusk · one",
    what: { ko: "글과 이미지가 섞인 설명 구획.", en: "A prose-and-image section." },
    when: { ko: "히어로에서 다 못한 이야기를 이어갈 때.", en: "For continuing what the hero couldn't finish." },
  },
  {
    id: "tailark-dusk-content-three",
    source: "tailark",
    kind: "content",
    variant: "dusk · three",
    what: { ko: "글과 이미지가 섞인 설명 구획.", en: "A prose-and-image section." },
    when: { ko: "히어로에서 다 못한 이야기를 이어갈 때.", en: "For continuing what the hero couldn't finish." },
  },
  {
    id: "tailark-dusk-content-two",
    source: "tailark",
    kind: "content",
    variant: "dusk · two",
    what: { ko: "글과 이미지가 섞인 설명 구획.", en: "A prose-and-image section." },
    when: { ko: "히어로에서 다 못한 이야기를 이어갈 때.", en: "For continuing what the hero couldn't finish." },
  },
  {
    id: "tailark-dusk-faqs-one",
    source: "tailark",
    kind: "faqs",
    variant: "dusk · one",
    what: { ko: "반복되는 질문을 접어 둔 목록.", en: "Recurring questions, folded away." },
    when: { ko: "지원 문의가 같은 내용으로 계속 올 때. 답이 세 개 미만이면 굳이 접지 않는다.", en: "When support keeps getting the same question. Under three answers, don't fold them." },
  },
  {
    id: "tailark-dusk-features-five",
    source: "tailark",
    kind: "features",
    variant: "dusk · five",
    what: { ko: "제품이 무엇을 하는지 항목으로 나눠 보인다.", en: "What the product does, broken into items." },
    when: { ko: "히어로 바로 아래. 항목마다 '그래서 뭐가 좋은지' 가 없으면 나열에 그친다.", en: "Right under the hero. Without a 'so what' per item, it's just a list." },
  },
  {
    id: "tailark-dusk-features-four",
    source: "tailark",
    kind: "features",
    variant: "dusk · four",
    what: { ko: "제품이 무엇을 하는지 항목으로 나눠 보인다.", en: "What the product does, broken into items." },
    when: { ko: "히어로 바로 아래. 항목마다 '그래서 뭐가 좋은지' 가 없으면 나열에 그친다.", en: "Right under the hero. Without a 'so what' per item, it's just a list." },
  },
  {
    id: "tailark-dusk-features-one",
    source: "tailark",
    kind: "features",
    variant: "dusk · one",
    what: { ko: "제품이 무엇을 하는지 항목으로 나눠 보인다.", en: "What the product does, broken into items." },
    when: { ko: "히어로 바로 아래. 항목마다 '그래서 뭐가 좋은지' 가 없으면 나열에 그친다.", en: "Right under the hero. Without a 'so what' per item, it's just a list." },
  },
  {
    id: "tailark-dusk-features-seven",
    source: "tailark",
    kind: "features",
    variant: "dusk · seven",
    what: { ko: "제품이 무엇을 하는지 항목으로 나눠 보인다.", en: "What the product does, broken into items." },
    when: { ko: "히어로 바로 아래. 항목마다 '그래서 뭐가 좋은지' 가 없으면 나열에 그친다.", en: "Right under the hero. Without a 'so what' per item, it's just a list." },
  },
  {
    id: "tailark-dusk-features-six",
    source: "tailark",
    kind: "features",
    variant: "dusk · six",
    what: { ko: "제품이 무엇을 하는지 항목으로 나눠 보인다.", en: "What the product does, broken into items." },
    when: { ko: "히어로 바로 아래. 항목마다 '그래서 뭐가 좋은지' 가 없으면 나열에 그친다.", en: "Right under the hero. Without a 'so what' per item, it's just a list." },
  },
  {
    id: "tailark-dusk-features-three",
    source: "tailark",
    kind: "features",
    variant: "dusk · three",
    what: { ko: "제품이 무엇을 하는지 항목으로 나눠 보인다.", en: "What the product does, broken into items." },
    when: { ko: "히어로 바로 아래. 항목마다 '그래서 뭐가 좋은지' 가 없으면 나열에 그친다.", en: "Right under the hero. Without a 'so what' per item, it's just a list." },
  },
  {
    id: "tailark-dusk-features-two",
    source: "tailark",
    kind: "features",
    variant: "dusk · two",
    what: { ko: "제품이 무엇을 하는지 항목으로 나눠 보인다.", en: "What the product does, broken into items." },
    when: { ko: "히어로 바로 아래. 항목마다 '그래서 뭐가 좋은지' 가 없으면 나열에 그친다.", en: "Right under the hero. Without a 'so what' per item, it's just a list." },
  },
  {
    id: "tailark-dusk-footer-one",
    source: "tailark",
    kind: "footer",
    variant: "dusk · one",
    what: { ko: "페이지 맨 아래의 링크 묶음.", en: "The link block at the bottom." },
    when: { ko: "법적 고지 · 연락처 · 부차 링크가 갈 곳. 여기 있는 것은 아무도 안 찾는다고 가정한다.", en: "Legal, contact, secondary links. Assume nobody goes looking here." },
  },
  {
    id: "tailark-dusk-footer-two",
    source: "tailark",
    kind: "footer",
    variant: "dusk · two",
    what: { ko: "페이지 맨 아래의 링크 묶음.", en: "The link block at the bottom." },
    when: { ko: "법적 고지 · 연락처 · 부차 링크가 갈 곳. 여기 있는 것은 아무도 안 찾는다고 가정한다.", en: "Legal, contact, secondary links. Assume nobody goes looking here." },
  },
  {
    id: "tailark-dusk-hero-section-eight",
    source: "tailark",
    kind: "hero-section",
    variant: "dusk · eight",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-dusk-hero-section-five",
    source: "tailark",
    kind: "hero-section",
    variant: "dusk · five",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-dusk-hero-section-four",
    source: "tailark",
    kind: "hero-section",
    variant: "dusk · four",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-dusk-hero-section-nine",
    source: "tailark",
    kind: "hero-section",
    variant: "dusk · nine",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-dusk-hero-section-one",
    source: "tailark",
    kind: "hero-section",
    variant: "dusk · one",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-dusk-hero-section-seven",
    source: "tailark",
    kind: "hero-section",
    variant: "dusk · seven",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-dusk-hero-section-six",
    source: "tailark",
    kind: "hero-section",
    variant: "dusk · six",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-dusk-hero-section-ten",
    source: "tailark",
    kind: "hero-section",
    variant: "dusk · ten",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-dusk-hero-section-three",
    source: "tailark",
    kind: "hero-section",
    variant: "dusk · three",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-dusk-hero-section-two",
    source: "tailark",
    kind: "hero-section",
    variant: "dusk · two",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-dusk-integrations-one",
    source: "tailark",
    kind: "integrations",
    variant: "dusk · one",
    what: { ko: "연동되는 서비스의 로고를 늘어놓는다.", en: "Logos of what it connects to." },
    when: { ko: "'이미 쓰는 도구와 붙는다' 가 구매 이유인 제품.", en: "For products where 'it fits your existing stack' is the reason to buy." },
  },
  {
    id: "tailark-dusk-logo-cloud-four",
    source: "tailark",
    kind: "logo-cloud",
    variant: "dusk · four",
    what: { ko: "고객사 로고를 한 줄로.", en: "Customer logos in a row." },
    when: { ko: "쓸 수 있는 로고가 여섯 개 이상일 때. 세 개면 오히려 규모가 작아 보인다.", en: "Six or more. With three, it makes you look smaller." },
  },
  {
    id: "tailark-dusk-logo-cloud-one",
    source: "tailark",
    kind: "logo-cloud",
    variant: "dusk · one",
    what: { ko: "고객사 로고를 한 줄로.", en: "Customer logos in a row." },
    when: { ko: "쓸 수 있는 로고가 여섯 개 이상일 때. 세 개면 오히려 규모가 작아 보인다.", en: "Six or more. With three, it makes you look smaller." },
  },
  {
    id: "tailark-dusk-logo-cloud-three",
    source: "tailark",
    kind: "logo-cloud",
    variant: "dusk · three",
    what: { ko: "고객사 로고를 한 줄로.", en: "Customer logos in a row." },
    when: { ko: "쓸 수 있는 로고가 여섯 개 이상일 때. 세 개면 오히려 규모가 작아 보인다.", en: "Six or more. With three, it makes you look smaller." },
  },
  {
    id: "tailark-dusk-logo-cloud-two",
    source: "tailark",
    kind: "logo-cloud",
    variant: "dusk · two",
    what: { ko: "고객사 로고를 한 줄로.", en: "Customer logos in a row." },
    when: { ko: "쓸 수 있는 로고가 여섯 개 이상일 때. 세 개면 오히려 규모가 작아 보인다.", en: "Six or more. With three, it makes you look smaller." },
  },
  {
    id: "tailark-dusk-pricing-one",
    source: "tailark",
    kind: "pricing",
    variant: "dusk · one",
    what: { ko: "요금제를 나란히 놓고 고르게 하는 표.", en: "Plans side by side." },
    when: { ko: "안이 3개를 넘으면 비교가 안 된다. 그 이상이면 비교표(comparator)로 바꾼다.", en: "Past three tiers, comparison stops working — switch to a comparator." },
  },
  {
    id: "tailark-dusk-pricing-two",
    source: "tailark",
    kind: "pricing",
    variant: "dusk · two",
    what: { ko: "요금제를 나란히 놓고 고르게 하는 표.", en: "Plans side by side." },
    when: { ko: "안이 3개를 넘으면 비교가 안 된다. 그 이상이면 비교표(comparator)로 바꾼다.", en: "Past three tiers, comparison stops working — switch to a comparator." },
  },
  {
    id: "tailark-dusk-stats-one",
    source: "tailark",
    kind: "stats",
    variant: "dusk · one",
    what: { ko: "숫자 서너 개로 규모를 보인다.", en: "Three or four numbers showing scale." },
    when: { ko: "실제 숫자가 있을 때만. 없는 숫자를 지어내면 그 페이지 전체의 신뢰가 무너진다.", en: "Only with real numbers. Invented ones cost you the whole page's credibility." },
  },
  {
    id: "tailark-dusk-stats-two",
    source: "tailark",
    kind: "stats",
    variant: "dusk · two",
    what: { ko: "숫자 서너 개로 규모를 보인다.", en: "Three or four numbers showing scale." },
    when: { ko: "실제 숫자가 있을 때만. 없는 숫자를 지어내면 그 페이지 전체의 신뢰가 무너진다.", en: "Only with real numbers. Invented ones cost you the whole page's credibility." },
  },
  {
    id: "tailark-dusk-team-one",
    source: "tailark",
    kind: "team",
    variant: "dusk · one",
    what: { ko: "만드는 사람들을 보인다.", en: "The people behind it." },
    when: { ko: "사람이 곧 신뢰인 업종 — 에이전시, 컨설팅, 의료.", en: "Where people are the trust — agencies, consulting, care." },
  },
  {
    id: "tailark-dusk-team-two",
    source: "tailark",
    kind: "team",
    variant: "dusk · two",
    what: { ko: "만드는 사람들을 보인다.", en: "The people behind it." },
    when: { ko: "사람이 곧 신뢰인 업종 — 에이전시, 컨설팅, 의료.", en: "Where people are the trust — agencies, consulting, care." },
  },
  {
    id: "tailark-dusk-testimonials-one",
    source: "tailark",
    kind: "testimonials",
    variant: "dusk · one",
    what: { ko: "쓴 사람의 말을 인용한다.", en: "Quotes from people who used it." },
    when: { ko: "제품 설명만으로 못 넘는 신뢰의 벽이 있을 때. 실명과 소속이 없으면 효과가 없다.", en: "For the trust gap your own copy can't cross. Without a real name and org, it does nothing." },
  },
  {
    id: "tailark-dusk-testimonials-two",
    source: "tailark",
    kind: "testimonials",
    variant: "dusk · two",
    what: { ko: "쓴 사람의 말을 인용한다.", en: "Quotes from people who used it." },
    when: { ko: "제품 설명만으로 못 넘는 신뢰의 벽이 있을 때. 실명과 소속이 없으면 효과가 없다.", en: "For the trust gap your own copy can't cross. Without a real name and org, it does nothing." },
  },
  {
    id: "tailark-mist-call-to-action-one",
    source: "tailark",
    kind: "call-to-action",
    variant: "mist · one",
    what: { ko: "페이지 끝에서 다음 행동 하나로 몰아준다.", en: "The closing push toward one action." },
    when: { ko: "스크롤을 끝까지 내린 사람에게 마지막으로 묻는 자리. 선택지를 둘 이상 두지 않는다.", en: "The last ask for someone who scrolled all the way. Never more than one option." },
  },
  {
    id: "tailark-mist-call-to-action-three",
    source: "tailark",
    kind: "call-to-action",
    variant: "mist · three",
    what: { ko: "페이지 끝에서 다음 행동 하나로 몰아준다.", en: "The closing push toward one action." },
    when: { ko: "스크롤을 끝까지 내린 사람에게 마지막으로 묻는 자리. 선택지를 둘 이상 두지 않는다.", en: "The last ask for someone who scrolled all the way. Never more than one option." },
  },
  {
    id: "tailark-mist-call-to-action-two",
    source: "tailark",
    kind: "call-to-action",
    variant: "mist · two",
    what: { ko: "페이지 끝에서 다음 행동 하나로 몰아준다.", en: "The closing push toward one action." },
    when: { ko: "스크롤을 끝까지 내린 사람에게 마지막으로 묻는 자리. 선택지를 둘 이상 두지 않는다.", en: "The last ask for someone who scrolled all the way. Never more than one option." },
  },
  {
    id: "tailark-mist-comparator-one",
    source: "tailark",
    kind: "comparator",
    variant: "mist · one",
    what: { ko: "기능별로 있고 없음을 표로 대조한다.", en: "A feature-by-feature table." },
    when: { ko: "요금제가 넷 이상이거나 항목이 많아 카드로는 안 될 때.", en: "When there are four or more plans, or too many rows for cards." },
  },
  {
    id: "tailark-mist-contact-one",
    source: "tailark",
    kind: "contact",
    variant: "mist · one",
    what: { ko: "연락 폼 또는 연락처.", en: "A contact form or details." },
    when: { ko: "제품이 아직 셀프서비스가 아닐 때. 응답 시간을 함께 적는다.", en: "When the product isn't self-serve yet. State the response time." },
  },
  {
    id: "tailark-mist-content-four",
    source: "tailark",
    kind: "content",
    variant: "mist · four",
    what: { ko: "글과 이미지가 섞인 설명 구획.", en: "A prose-and-image section." },
    when: { ko: "히어로에서 다 못한 이야기를 이어갈 때.", en: "For continuing what the hero couldn't finish." },
  },
  {
    id: "tailark-mist-content-one",
    source: "tailark",
    kind: "content",
    variant: "mist · one",
    what: { ko: "글과 이미지가 섞인 설명 구획.", en: "A prose-and-image section." },
    when: { ko: "히어로에서 다 못한 이야기를 이어갈 때.", en: "For continuing what the hero couldn't finish." },
  },
  {
    id: "tailark-mist-content-three",
    source: "tailark",
    kind: "content",
    variant: "mist · three",
    what: { ko: "글과 이미지가 섞인 설명 구획.", en: "A prose-and-image section." },
    when: { ko: "히어로에서 다 못한 이야기를 이어갈 때.", en: "For continuing what the hero couldn't finish." },
  },
  {
    id: "tailark-mist-content-two",
    source: "tailark",
    kind: "content",
    variant: "mist · two",
    what: { ko: "글과 이미지가 섞인 설명 구획.", en: "A prose-and-image section." },
    when: { ko: "히어로에서 다 못한 이야기를 이어갈 때.", en: "For continuing what the hero couldn't finish." },
  },
  {
    id: "tailark-mist-faqs-one",
    source: "tailark",
    kind: "faqs",
    variant: "mist · one",
    what: { ko: "반복되는 질문을 접어 둔 목록.", en: "Recurring questions, folded away." },
    when: { ko: "지원 문의가 같은 내용으로 계속 올 때. 답이 세 개 미만이면 굳이 접지 않는다.", en: "When support keeps getting the same question. Under three answers, don't fold them." },
  },
  {
    id: "tailark-mist-faqs-three",
    source: "tailark",
    kind: "faqs",
    variant: "mist · three",
    what: { ko: "반복되는 질문을 접어 둔 목록.", en: "Recurring questions, folded away." },
    when: { ko: "지원 문의가 같은 내용으로 계속 올 때. 답이 세 개 미만이면 굳이 접지 않는다.", en: "When support keeps getting the same question. Under three answers, don't fold them." },
  },
  {
    id: "tailark-mist-faqs-two",
    source: "tailark",
    kind: "faqs",
    variant: "mist · two",
    what: { ko: "반복되는 질문을 접어 둔 목록.", en: "Recurring questions, folded away." },
    when: { ko: "지원 문의가 같은 내용으로 계속 올 때. 답이 세 개 미만이면 굳이 접지 않는다.", en: "When support keeps getting the same question. Under three answers, don't fold them." },
  },
  {
    id: "tailark-mist-features-eight",
    source: "tailark",
    kind: "features",
    variant: "mist · eight",
    what: { ko: "제품이 무엇을 하는지 항목으로 나눠 보인다.", en: "What the product does, broken into items." },
    when: { ko: "히어로 바로 아래. 항목마다 '그래서 뭐가 좋은지' 가 없으면 나열에 그친다.", en: "Right under the hero. Without a 'so what' per item, it's just a list." },
  },
  {
    id: "tailark-mist-features-eleven",
    source: "tailark",
    kind: "features",
    variant: "mist · eleven",
    what: { ko: "제품이 무엇을 하는지 항목으로 나눠 보인다.", en: "What the product does, broken into items." },
    when: { ko: "히어로 바로 아래. 항목마다 '그래서 뭐가 좋은지' 가 없으면 나열에 그친다.", en: "Right under the hero. Without a 'so what' per item, it's just a list." },
  },
  {
    id: "tailark-mist-features-five",
    source: "tailark",
    kind: "features",
    variant: "mist · five",
    what: { ko: "제품이 무엇을 하는지 항목으로 나눠 보인다.", en: "What the product does, broken into items." },
    when: { ko: "히어로 바로 아래. 항목마다 '그래서 뭐가 좋은지' 가 없으면 나열에 그친다.", en: "Right under the hero. Without a 'so what' per item, it's just a list." },
  },
  {
    id: "tailark-mist-features-four",
    source: "tailark",
    kind: "features",
    variant: "mist · four",
    what: { ko: "제품이 무엇을 하는지 항목으로 나눠 보인다.", en: "What the product does, broken into items." },
    when: { ko: "히어로 바로 아래. 항목마다 '그래서 뭐가 좋은지' 가 없으면 나열에 그친다.", en: "Right under the hero. Without a 'so what' per item, it's just a list." },
  },
  {
    id: "tailark-mist-features-nine",
    source: "tailark",
    kind: "features",
    variant: "mist · nine",
    what: { ko: "제품이 무엇을 하는지 항목으로 나눠 보인다.", en: "What the product does, broken into items." },
    when: { ko: "히어로 바로 아래. 항목마다 '그래서 뭐가 좋은지' 가 없으면 나열에 그친다.", en: "Right under the hero. Without a 'so what' per item, it's just a list." },
  },
  {
    id: "tailark-mist-features-one",
    source: "tailark",
    kind: "features",
    variant: "mist · one",
    what: { ko: "제품이 무엇을 하는지 항목으로 나눠 보인다.", en: "What the product does, broken into items." },
    when: { ko: "히어로 바로 아래. 항목마다 '그래서 뭐가 좋은지' 가 없으면 나열에 그친다.", en: "Right under the hero. Without a 'so what' per item, it's just a list." },
  },
  {
    id: "tailark-mist-features-seven",
    source: "tailark",
    kind: "features",
    variant: "mist · seven",
    what: { ko: "제품이 무엇을 하는지 항목으로 나눠 보인다.", en: "What the product does, broken into items." },
    when: { ko: "히어로 바로 아래. 항목마다 '그래서 뭐가 좋은지' 가 없으면 나열에 그친다.", en: "Right under the hero. Without a 'so what' per item, it's just a list." },
  },
  {
    id: "tailark-mist-features-six",
    source: "tailark",
    kind: "features",
    variant: "mist · six",
    what: { ko: "제품이 무엇을 하는지 항목으로 나눠 보인다.", en: "What the product does, broken into items." },
    when: { ko: "히어로 바로 아래. 항목마다 '그래서 뭐가 좋은지' 가 없으면 나열에 그친다.", en: "Right under the hero. Without a 'so what' per item, it's just a list." },
  },
  {
    id: "tailark-mist-features-ten",
    source: "tailark",
    kind: "features",
    variant: "mist · ten",
    what: { ko: "제품이 무엇을 하는지 항목으로 나눠 보인다.", en: "What the product does, broken into items." },
    when: { ko: "히어로 바로 아래. 항목마다 '그래서 뭐가 좋은지' 가 없으면 나열에 그친다.", en: "Right under the hero. Without a 'so what' per item, it's just a list." },
  },
  {
    id: "tailark-mist-features-three",
    source: "tailark",
    kind: "features",
    variant: "mist · three",
    what: { ko: "제품이 무엇을 하는지 항목으로 나눠 보인다.", en: "What the product does, broken into items." },
    when: { ko: "히어로 바로 아래. 항목마다 '그래서 뭐가 좋은지' 가 없으면 나열에 그친다.", en: "Right under the hero. Without a 'so what' per item, it's just a list." },
  },
  {
    id: "tailark-mist-features-two",
    source: "tailark",
    kind: "features",
    variant: "mist · two",
    what: { ko: "제품이 무엇을 하는지 항목으로 나눠 보인다.", en: "What the product does, broken into items." },
    when: { ko: "히어로 바로 아래. 항목마다 '그래서 뭐가 좋은지' 가 없으면 나열에 그친다.", en: "Right under the hero. Without a 'so what' per item, it's just a list." },
  },
  {
    id: "tailark-mist-footer-four",
    source: "tailark",
    kind: "footer",
    variant: "mist · four",
    what: { ko: "페이지 맨 아래의 링크 묶음.", en: "The link block at the bottom." },
    when: { ko: "법적 고지 · 연락처 · 부차 링크가 갈 곳. 여기 있는 것은 아무도 안 찾는다고 가정한다.", en: "Legal, contact, secondary links. Assume nobody goes looking here." },
  },
  {
    id: "tailark-mist-footer-one",
    source: "tailark",
    kind: "footer",
    variant: "mist · one",
    what: { ko: "페이지 맨 아래의 링크 묶음.", en: "The link block at the bottom." },
    when: { ko: "법적 고지 · 연락처 · 부차 링크가 갈 곳. 여기 있는 것은 아무도 안 찾는다고 가정한다.", en: "Legal, contact, secondary links. Assume nobody goes looking here." },
  },
  {
    id: "tailark-mist-footer-three",
    source: "tailark",
    kind: "footer",
    variant: "mist · three",
    what: { ko: "페이지 맨 아래의 링크 묶음.", en: "The link block at the bottom." },
    when: { ko: "법적 고지 · 연락처 · 부차 링크가 갈 곳. 여기 있는 것은 아무도 안 찾는다고 가정한다.", en: "Legal, contact, secondary links. Assume nobody goes looking here." },
  },
  {
    id: "tailark-mist-footer-two",
    source: "tailark",
    kind: "footer",
    variant: "mist · two",
    what: { ko: "페이지 맨 아래의 링크 묶음.", en: "The link block at the bottom." },
    when: { ko: "법적 고지 · 연락처 · 부차 링크가 갈 곳. 여기 있는 것은 아무도 안 찾는다고 가정한다.", en: "Legal, contact, secondary links. Assume nobody goes looking here." },
  },
  {
    id: "tailark-mist-forgot-password-one",
    source: "tailark",
    kind: "forgot-password",
    variant: "mist · one",
    what: { ko: "비밀번호 재설정 진입.", en: "Password reset entry." },
    when: { ko: "로그인 화면과 짝을 이룬다. 메일이 늦게 올 때의 안내가 필요하다.", en: "Pairs with sign-in. Needs copy for when the mail is slow." },
  },
  {
    id: "tailark-mist-hero-section-five",
    source: "tailark",
    kind: "hero-section",
    variant: "mist · five",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-mist-hero-section-four",
    source: "tailark",
    kind: "hero-section",
    variant: "mist · four",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-mist-hero-section-one",
    source: "tailark",
    kind: "hero-section",
    variant: "mist · one",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-mist-hero-section-six",
    source: "tailark",
    kind: "hero-section",
    variant: "mist · six",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-mist-hero-section-three",
    source: "tailark",
    kind: "hero-section",
    variant: "mist · three",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-mist-hero-section-two",
    source: "tailark",
    kind: "hero-section",
    variant: "mist · two",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-mist-integrations-one",
    source: "tailark",
    kind: "integrations",
    variant: "mist · one",
    what: { ko: "연동되는 서비스의 로고를 늘어놓는다.", en: "Logos of what it connects to." },
    when: { ko: "'이미 쓰는 도구와 붙는다' 가 구매 이유인 제품.", en: "For products where 'it fits your existing stack' is the reason to buy." },
  },
  {
    id: "tailark-mist-integrations-three",
    source: "tailark",
    kind: "integrations",
    variant: "mist · three",
    what: { ko: "연동되는 서비스의 로고를 늘어놓는다.", en: "Logos of what it connects to." },
    when: { ko: "'이미 쓰는 도구와 붙는다' 가 구매 이유인 제품.", en: "For products where 'it fits your existing stack' is the reason to buy." },
  },
  {
    id: "tailark-mist-integrations-two",
    source: "tailark",
    kind: "integrations",
    variant: "mist · two",
    what: { ko: "연동되는 서비스의 로고를 늘어놓는다.", en: "Logos of what it connects to." },
    when: { ko: "'이미 쓰는 도구와 붙는다' 가 구매 이유인 제품.", en: "For products where 'it fits your existing stack' is the reason to buy." },
  },
  {
    id: "tailark-mist-login-one",
    source: "tailark",
    kind: "login",
    variant: "mist · one",
    what: { ko: "로그인 화면.", en: "A sign-in screen." },
    when: { ko: "공식 블록에도 5종이 있다. 이쪽은 마케팅 페이지와 톤을 맞추고 싶을 때.", en: "The official set has five. Use these when the tone must match the marketing site." },
  },
  {
    id: "tailark-mist-logo-cloud-one",
    source: "tailark",
    kind: "logo-cloud",
    variant: "mist · one",
    what: { ko: "고객사 로고를 한 줄로.", en: "Customer logos in a row." },
    when: { ko: "쓸 수 있는 로고가 여섯 개 이상일 때. 세 개면 오히려 규모가 작아 보인다.", en: "Six or more. With three, it makes you look smaller." },
  },
  {
    id: "tailark-mist-logo-cloud-two",
    source: "tailark",
    kind: "logo-cloud",
    variant: "mist · two",
    what: { ko: "고객사 로고를 한 줄로.", en: "Customer logos in a row." },
    when: { ko: "쓸 수 있는 로고가 여섯 개 이상일 때. 세 개면 오히려 규모가 작아 보인다.", en: "Six or more. With three, it makes you look smaller." },
  },
  {
    id: "tailark-mist-pricing-one",
    source: "tailark",
    kind: "pricing",
    variant: "mist · one",
    what: { ko: "요금제를 나란히 놓고 고르게 하는 표.", en: "Plans side by side." },
    when: { ko: "안이 3개를 넘으면 비교가 안 된다. 그 이상이면 비교표(comparator)로 바꾼다.", en: "Past three tiers, comparison stops working — switch to a comparator." },
  },
  {
    id: "tailark-mist-pricing-two",
    source: "tailark",
    kind: "pricing",
    variant: "mist · two",
    what: { ko: "요금제를 나란히 놓고 고르게 하는 표.", en: "Plans side by side." },
    when: { ko: "안이 3개를 넘으면 비교가 안 된다. 그 이상이면 비교표(comparator)로 바꾼다.", en: "Past three tiers, comparison stops working — switch to a comparator." },
  },
  {
    id: "tailark-mist-sign-up-one",
    source: "tailark",
    kind: "sign-up",
    variant: "mist · one",
    what: { ko: "가입 화면.", en: "A sign-up screen." },
    when: { ko: "위와 같다 — 톤을 맞출 때.", en: "Same as above — when tone matters." },
  },
  {
    id: "tailark-mist-stats-four",
    source: "tailark",
    kind: "stats",
    variant: "mist · four",
    what: { ko: "숫자 서너 개로 규모를 보인다.", en: "Three or four numbers showing scale." },
    when: { ko: "실제 숫자가 있을 때만. 없는 숫자를 지어내면 그 페이지 전체의 신뢰가 무너진다.", en: "Only with real numbers. Invented ones cost you the whole page's credibility." },
  },
  {
    id: "tailark-mist-stats-one",
    source: "tailark",
    kind: "stats",
    variant: "mist · one",
    what: { ko: "숫자 서너 개로 규모를 보인다.", en: "Three or four numbers showing scale." },
    when: { ko: "실제 숫자가 있을 때만. 없는 숫자를 지어내면 그 페이지 전체의 신뢰가 무너진다.", en: "Only with real numbers. Invented ones cost you the whole page's credibility." },
  },
  {
    id: "tailark-mist-stats-three",
    source: "tailark",
    kind: "stats",
    variant: "mist · three",
    what: { ko: "숫자 서너 개로 규모를 보인다.", en: "Three or four numbers showing scale." },
    when: { ko: "실제 숫자가 있을 때만. 없는 숫자를 지어내면 그 페이지 전체의 신뢰가 무너진다.", en: "Only with real numbers. Invented ones cost you the whole page's credibility." },
  },
  {
    id: "tailark-mist-stats-two",
    source: "tailark",
    kind: "stats",
    variant: "mist · two",
    what: { ko: "숫자 서너 개로 규모를 보인다.", en: "Three or four numbers showing scale." },
    when: { ko: "실제 숫자가 있을 때만. 없는 숫자를 지어내면 그 페이지 전체의 신뢰가 무너진다.", en: "Only with real numbers. Invented ones cost you the whole page's credibility." },
  },
  {
    id: "tailark-mist-team-one",
    source: "tailark",
    kind: "team",
    variant: "mist · one",
    what: { ko: "만드는 사람들을 보인다.", en: "The people behind it." },
    when: { ko: "사람이 곧 신뢰인 업종 — 에이전시, 컨설팅, 의료.", en: "Where people are the trust — agencies, consulting, care." },
  },
  {
    id: "tailark-mist-team-two",
    source: "tailark",
    kind: "team",
    variant: "mist · two",
    what: { ko: "만드는 사람들을 보인다.", en: "The people behind it." },
    when: { ko: "사람이 곧 신뢰인 업종 — 에이전시, 컨설팅, 의료.", en: "Where people are the trust — agencies, consulting, care." },
  },
  {
    id: "tailark-mist-testimonials-five",
    source: "tailark",
    kind: "testimonials",
    variant: "mist · five",
    what: { ko: "쓴 사람의 말을 인용한다.", en: "Quotes from people who used it." },
    when: { ko: "제품 설명만으로 못 넘는 신뢰의 벽이 있을 때. 실명과 소속이 없으면 효과가 없다.", en: "For the trust gap your own copy can't cross. Without a real name and org, it does nothing." },
  },
  {
    id: "tailark-mist-testimonials-four",
    source: "tailark",
    kind: "testimonials",
    variant: "mist · four",
    what: { ko: "쓴 사람의 말을 인용한다.", en: "Quotes from people who used it." },
    when: { ko: "제품 설명만으로 못 넘는 신뢰의 벽이 있을 때. 실명과 소속이 없으면 효과가 없다.", en: "For the trust gap your own copy can't cross. Without a real name and org, it does nothing." },
  },
  {
    id: "tailark-mist-testimonials-one",
    source: "tailark",
    kind: "testimonials",
    variant: "mist · one",
    what: { ko: "쓴 사람의 말을 인용한다.", en: "Quotes from people who used it." },
    when: { ko: "제품 설명만으로 못 넘는 신뢰의 벽이 있을 때. 실명과 소속이 없으면 효과가 없다.", en: "For the trust gap your own copy can't cross. Without a real name and org, it does nothing." },
  },
  {
    id: "tailark-mist-testimonials-three",
    source: "tailark",
    kind: "testimonials",
    variant: "mist · three",
    what: { ko: "쓴 사람의 말을 인용한다.", en: "Quotes from people who used it." },
    when: { ko: "제품 설명만으로 못 넘는 신뢰의 벽이 있을 때. 실명과 소속이 없으면 효과가 없다.", en: "For the trust gap your own copy can't cross. Without a real name and org, it does nothing." },
  },
  {
    id: "tailark-mist-testimonials-two",
    source: "tailark",
    kind: "testimonials",
    variant: "mist · two",
    what: { ko: "쓴 사람의 말을 인용한다.", en: "Quotes from people who used it." },
    when: { ko: "제품 설명만으로 못 넘는 신뢰의 벽이 있을 때. 실명과 소속이 없으면 효과가 없다.", en: "For the trust gap your own copy can't cross. Without a real name and org, it does nothing." },
  },
  {
    id: "tailark-veil-call-to-action-four",
    source: "tailark",
    kind: "call-to-action",
    variant: "veil · four",
    what: { ko: "페이지 끝에서 다음 행동 하나로 몰아준다.", en: "The closing push toward one action." },
    when: { ko: "스크롤을 끝까지 내린 사람에게 마지막으로 묻는 자리. 선택지를 둘 이상 두지 않는다.", en: "The last ask for someone who scrolled all the way. Never more than one option." },
  },
  {
    id: "tailark-veil-call-to-action-one",
    source: "tailark",
    kind: "call-to-action",
    variant: "veil · one",
    what: { ko: "페이지 끝에서 다음 행동 하나로 몰아준다.", en: "The closing push toward one action." },
    when: { ko: "스크롤을 끝까지 내린 사람에게 마지막으로 묻는 자리. 선택지를 둘 이상 두지 않는다.", en: "The last ask for someone who scrolled all the way. Never more than one option." },
  },
  {
    id: "tailark-veil-call-to-action-three",
    source: "tailark",
    kind: "call-to-action",
    variant: "veil · three",
    what: { ko: "페이지 끝에서 다음 행동 하나로 몰아준다.", en: "The closing push toward one action." },
    when: { ko: "스크롤을 끝까지 내린 사람에게 마지막으로 묻는 자리. 선택지를 둘 이상 두지 않는다.", en: "The last ask for someone who scrolled all the way. Never more than one option." },
  },
  {
    id: "tailark-veil-call-to-action-two",
    source: "tailark",
    kind: "call-to-action",
    variant: "veil · two",
    what: { ko: "페이지 끝에서 다음 행동 하나로 몰아준다.", en: "The closing push toward one action." },
    when: { ko: "스크롤을 끝까지 내린 사람에게 마지막으로 묻는 자리. 선택지를 둘 이상 두지 않는다.", en: "The last ask for someone who scrolled all the way. Never more than one option." },
  },
  {
    id: "tailark-veil-comparator-one",
    source: "tailark",
    kind: "comparator",
    variant: "veil · one",
    what: { ko: "기능별로 있고 없음을 표로 대조한다.", en: "A feature-by-feature table." },
    when: { ko: "요금제가 넷 이상이거나 항목이 많아 카드로는 안 될 때.", en: "When there are four or more plans, or too many rows for cards." },
  },
  {
    id: "tailark-veil-comparator-three",
    source: "tailark",
    kind: "comparator",
    variant: "veil · three",
    what: { ko: "기능별로 있고 없음을 표로 대조한다.", en: "A feature-by-feature table." },
    when: { ko: "요금제가 넷 이상이거나 항목이 많아 카드로는 안 될 때.", en: "When there are four or more plans, or too many rows for cards." },
  },
  {
    id: "tailark-veil-comparator-two",
    source: "tailark",
    kind: "comparator",
    variant: "veil · two",
    what: { ko: "기능별로 있고 없음을 표로 대조한다.", en: "A feature-by-feature table." },
    when: { ko: "요금제가 넷 이상이거나 항목이 많아 카드로는 안 될 때.", en: "When there are four or more plans, or too many rows for cards." },
  },
  {
    id: "tailark-veil-contact-one",
    source: "tailark",
    kind: "contact",
    variant: "veil · one",
    what: { ko: "연락 폼 또는 연락처.", en: "A contact form or details." },
    when: { ko: "제품이 아직 셀프서비스가 아닐 때. 응답 시간을 함께 적는다.", en: "When the product isn't self-serve yet. State the response time." },
  },
  {
    id: "tailark-veil-contact-two",
    source: "tailark",
    kind: "contact",
    variant: "veil · two",
    what: { ko: "연락 폼 또는 연락처.", en: "A contact form or details." },
    when: { ko: "제품이 아직 셀프서비스가 아닐 때. 응답 시간을 함께 적는다.", en: "When the product isn't self-serve yet. State the response time." },
  },
  {
    id: "tailark-veil-content-one",
    source: "tailark",
    kind: "content",
    variant: "veil · one",
    what: { ko: "글과 이미지가 섞인 설명 구획.", en: "A prose-and-image section." },
    when: { ko: "히어로에서 다 못한 이야기를 이어갈 때.", en: "For continuing what the hero couldn't finish." },
  },
  {
    id: "tailark-veil-content-three",
    source: "tailark",
    kind: "content",
    variant: "veil · three",
    what: { ko: "글과 이미지가 섞인 설명 구획.", en: "A prose-and-image section." },
    when: { ko: "히어로에서 다 못한 이야기를 이어갈 때.", en: "For continuing what the hero couldn't finish." },
  },
  {
    id: "tailark-veil-content-two",
    source: "tailark",
    kind: "content",
    variant: "veil · two",
    what: { ko: "글과 이미지가 섞인 설명 구획.", en: "A prose-and-image section." },
    when: { ko: "히어로에서 다 못한 이야기를 이어갈 때.", en: "For continuing what the hero couldn't finish." },
  },
  {
    id: "tailark-veil-faqs-five",
    source: "tailark",
    kind: "faqs",
    variant: "veil · five",
    what: { ko: "반복되는 질문을 접어 둔 목록.", en: "Recurring questions, folded away." },
    when: { ko: "지원 문의가 같은 내용으로 계속 올 때. 답이 세 개 미만이면 굳이 접지 않는다.", en: "When support keeps getting the same question. Under three answers, don't fold them." },
  },
  {
    id: "tailark-veil-faqs-four",
    source: "tailark",
    kind: "faqs",
    variant: "veil · four",
    what: { ko: "반복되는 질문을 접어 둔 목록.", en: "Recurring questions, folded away." },
    when: { ko: "지원 문의가 같은 내용으로 계속 올 때. 답이 세 개 미만이면 굳이 접지 않는다.", en: "When support keeps getting the same question. Under three answers, don't fold them." },
  },
  {
    id: "tailark-veil-faqs-one",
    source: "tailark",
    kind: "faqs",
    variant: "veil · one",
    what: { ko: "반복되는 질문을 접어 둔 목록.", en: "Recurring questions, folded away." },
    when: { ko: "지원 문의가 같은 내용으로 계속 올 때. 답이 세 개 미만이면 굳이 접지 않는다.", en: "When support keeps getting the same question. Under three answers, don't fold them." },
  },
  {
    id: "tailark-veil-faqs-three",
    source: "tailark",
    kind: "faqs",
    variant: "veil · three",
    what: { ko: "반복되는 질문을 접어 둔 목록.", en: "Recurring questions, folded away." },
    when: { ko: "지원 문의가 같은 내용으로 계속 올 때. 답이 세 개 미만이면 굳이 접지 않는다.", en: "When support keeps getting the same question. Under three answers, don't fold them." },
  },
  {
    id: "tailark-veil-faqs-two",
    source: "tailark",
    kind: "faqs",
    variant: "veil · two",
    what: { ko: "반복되는 질문을 접어 둔 목록.", en: "Recurring questions, folded away." },
    when: { ko: "지원 문의가 같은 내용으로 계속 올 때. 답이 세 개 미만이면 굳이 접지 않는다.", en: "When support keeps getting the same question. Under three answers, don't fold them." },
  },
  {
    id: "tailark-veil-features-one",
    source: "tailark",
    kind: "features",
    variant: "veil · one",
    what: { ko: "제품이 무엇을 하는지 항목으로 나눠 보인다.", en: "What the product does, broken into items." },
    when: { ko: "히어로 바로 아래. 항목마다 '그래서 뭐가 좋은지' 가 없으면 나열에 그친다.", en: "Right under the hero. Without a 'so what' per item, it's just a list." },
  },
  {
    id: "tailark-veil-features-three",
    source: "tailark",
    kind: "features",
    variant: "veil · three",
    what: { ko: "제품이 무엇을 하는지 항목으로 나눠 보인다.", en: "What the product does, broken into items." },
    when: { ko: "히어로 바로 아래. 항목마다 '그래서 뭐가 좋은지' 가 없으면 나열에 그친다.", en: "Right under the hero. Without a 'so what' per item, it's just a list." },
  },
  {
    id: "tailark-veil-features-two",
    source: "tailark",
    kind: "features",
    variant: "veil · two",
    what: { ko: "제품이 무엇을 하는지 항목으로 나눠 보인다.", en: "What the product does, broken into items." },
    when: { ko: "히어로 바로 아래. 항목마다 '그래서 뭐가 좋은지' 가 없으면 나열에 그친다.", en: "Right under the hero. Without a 'so what' per item, it's just a list." },
  },
  {
    id: "tailark-veil-footer-five",
    source: "tailark",
    kind: "footer",
    variant: "veil · five",
    what: { ko: "페이지 맨 아래의 링크 묶음.", en: "The link block at the bottom." },
    when: { ko: "법적 고지 · 연락처 · 부차 링크가 갈 곳. 여기 있는 것은 아무도 안 찾는다고 가정한다.", en: "Legal, contact, secondary links. Assume nobody goes looking here." },
  },
  {
    id: "tailark-veil-footer-four",
    source: "tailark",
    kind: "footer",
    variant: "veil · four",
    what: { ko: "페이지 맨 아래의 링크 묶음.", en: "The link block at the bottom." },
    when: { ko: "법적 고지 · 연락처 · 부차 링크가 갈 곳. 여기 있는 것은 아무도 안 찾는다고 가정한다.", en: "Legal, contact, secondary links. Assume nobody goes looking here." },
  },
  {
    id: "tailark-veil-footer-one",
    source: "tailark",
    kind: "footer",
    variant: "veil · one",
    what: { ko: "페이지 맨 아래의 링크 묶음.", en: "The link block at the bottom." },
    when: { ko: "법적 고지 · 연락처 · 부차 링크가 갈 곳. 여기 있는 것은 아무도 안 찾는다고 가정한다.", en: "Legal, contact, secondary links. Assume nobody goes looking here." },
  },
  {
    id: "tailark-veil-footer-six",
    source: "tailark",
    kind: "footer",
    variant: "veil · six",
    what: { ko: "페이지 맨 아래의 링크 묶음.", en: "The link block at the bottom." },
    when: { ko: "법적 고지 · 연락처 · 부차 링크가 갈 곳. 여기 있는 것은 아무도 안 찾는다고 가정한다.", en: "Legal, contact, secondary links. Assume nobody goes looking here." },
  },
  {
    id: "tailark-veil-footer-three",
    source: "tailark",
    kind: "footer",
    variant: "veil · three",
    what: { ko: "페이지 맨 아래의 링크 묶음.", en: "The link block at the bottom." },
    when: { ko: "법적 고지 · 연락처 · 부차 링크가 갈 곳. 여기 있는 것은 아무도 안 찾는다고 가정한다.", en: "Legal, contact, secondary links. Assume nobody goes looking here." },
  },
  {
    id: "tailark-veil-footer-two",
    source: "tailark",
    kind: "footer",
    variant: "veil · two",
    what: { ko: "페이지 맨 아래의 링크 묶음.", en: "The link block at the bottom." },
    when: { ko: "법적 고지 · 연락처 · 부차 링크가 갈 곳. 여기 있는 것은 아무도 안 찾는다고 가정한다.", en: "Legal, contact, secondary links. Assume nobody goes looking here." },
  },
  {
    id: "tailark-veil-forgot-password-one",
    source: "tailark",
    kind: "forgot-password",
    variant: "veil · one",
    what: { ko: "비밀번호 재설정 진입.", en: "Password reset entry." },
    when: { ko: "로그인 화면과 짝을 이룬다. 메일이 늦게 올 때의 안내가 필요하다.", en: "Pairs with sign-in. Needs copy for when the mail is slow." },
  },
  {
    id: "tailark-veil-forgot-password-three",
    source: "tailark",
    kind: "forgot-password",
    variant: "veil · three",
    what: { ko: "비밀번호 재설정 진입.", en: "Password reset entry." },
    when: { ko: "로그인 화면과 짝을 이룬다. 메일이 늦게 올 때의 안내가 필요하다.", en: "Pairs with sign-in. Needs copy for when the mail is slow." },
  },
  {
    id: "tailark-veil-forgot-password-two",
    source: "tailark",
    kind: "forgot-password",
    variant: "veil · two",
    what: { ko: "비밀번호 재설정 진입.", en: "Password reset entry." },
    when: { ko: "로그인 화면과 짝을 이룬다. 메일이 늦게 올 때의 안내가 필요하다.", en: "Pairs with sign-in. Needs copy for when the mail is slow." },
  },
  {
    id: "tailark-veil-hero-section-five",
    source: "tailark",
    kind: "hero-section",
    variant: "veil · five",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-veil-hero-section-four",
    source: "tailark",
    kind: "hero-section",
    variant: "veil · four",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-veil-hero-section-one",
    source: "tailark",
    kind: "hero-section",
    variant: "veil · one",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-veil-hero-section-three",
    source: "tailark",
    kind: "hero-section",
    variant: "veil · three",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-veil-hero-section-two",
    source: "tailark",
    kind: "hero-section",
    variant: "veil · two",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-veil-integrations-one",
    source: "tailark",
    kind: "integrations",
    variant: "veil · one",
    what: { ko: "연동되는 서비스의 로고를 늘어놓는다.", en: "Logos of what it connects to." },
    when: { ko: "'이미 쓰는 도구와 붙는다' 가 구매 이유인 제품.", en: "For products where 'it fits your existing stack' is the reason to buy." },
  },
  {
    id: "tailark-veil-integrations-two",
    source: "tailark",
    kind: "integrations",
    variant: "veil · two",
    what: { ko: "연동되는 서비스의 로고를 늘어놓는다.", en: "Logos of what it connects to." },
    when: { ko: "'이미 쓰는 도구와 붙는다' 가 구매 이유인 제품.", en: "For products where 'it fits your existing stack' is the reason to buy." },
  },
  {
    id: "tailark-veil-login-one",
    source: "tailark",
    kind: "login",
    variant: "veil · one",
    what: { ko: "로그인 화면.", en: "A sign-in screen." },
    when: { ko: "공식 블록에도 5종이 있다. 이쪽은 마케팅 페이지와 톤을 맞추고 싶을 때.", en: "The official set has five. Use these when the tone must match the marketing site." },
  },
  {
    id: "tailark-veil-login-three",
    source: "tailark",
    kind: "login",
    variant: "veil · three",
    what: { ko: "로그인 화면.", en: "A sign-in screen." },
    when: { ko: "공식 블록에도 5종이 있다. 이쪽은 마케팅 페이지와 톤을 맞추고 싶을 때.", en: "The official set has five. Use these when the tone must match the marketing site." },
  },
  {
    id: "tailark-veil-login-two",
    source: "tailark",
    kind: "login",
    variant: "veil · two",
    what: { ko: "로그인 화면.", en: "A sign-in screen." },
    when: { ko: "공식 블록에도 5종이 있다. 이쪽은 마케팅 페이지와 톤을 맞추고 싶을 때.", en: "The official set has five. Use these when the tone must match the marketing site." },
  },
  {
    id: "tailark-veil-logo-cloud-one",
    source: "tailark",
    kind: "logo-cloud",
    variant: "veil · one",
    what: { ko: "고객사 로고를 한 줄로.", en: "Customer logos in a row." },
    when: { ko: "쓸 수 있는 로고가 여섯 개 이상일 때. 세 개면 오히려 규모가 작아 보인다.", en: "Six or more. With three, it makes you look smaller." },
  },
  {
    id: "tailark-veil-logo-cloud-two",
    source: "tailark",
    kind: "logo-cloud",
    variant: "veil · two",
    what: { ko: "고객사 로고를 한 줄로.", en: "Customer logos in a row." },
    when: { ko: "쓸 수 있는 로고가 여섯 개 이상일 때. 세 개면 오히려 규모가 작아 보인다.", en: "Six or more. With three, it makes you look smaller." },
  },
  {
    id: "tailark-veil-pricing-one",
    source: "tailark",
    kind: "pricing",
    variant: "veil · one",
    what: { ko: "요금제를 나란히 놓고 고르게 하는 표.", en: "Plans side by side." },
    when: { ko: "안이 3개를 넘으면 비교가 안 된다. 그 이상이면 비교표(comparator)로 바꾼다.", en: "Past three tiers, comparison stops working — switch to a comparator." },
  },
  {
    id: "tailark-veil-pricing-three",
    source: "tailark",
    kind: "pricing",
    variant: "veil · three",
    what: { ko: "요금제를 나란히 놓고 고르게 하는 표.", en: "Plans side by side." },
    when: { ko: "안이 3개를 넘으면 비교가 안 된다. 그 이상이면 비교표(comparator)로 바꾼다.", en: "Past three tiers, comparison stops working — switch to a comparator." },
  },
  {
    id: "tailark-veil-pricing-two",
    source: "tailark",
    kind: "pricing",
    variant: "veil · two",
    what: { ko: "요금제를 나란히 놓고 고르게 하는 표.", en: "Plans side by side." },
    when: { ko: "안이 3개를 넘으면 비교가 안 된다. 그 이상이면 비교표(comparator)로 바꾼다.", en: "Past three tiers, comparison stops working — switch to a comparator." },
  },
  {
    id: "tailark-veil-sign-up-one",
    source: "tailark",
    kind: "sign-up",
    variant: "veil · one",
    what: { ko: "가입 화면.", en: "A sign-up screen." },
    when: { ko: "위와 같다 — 톤을 맞출 때.", en: "Same as above — when tone matters." },
  },
  {
    id: "tailark-veil-sign-up-three",
    source: "tailark",
    kind: "sign-up",
    variant: "veil · three",
    what: { ko: "가입 화면.", en: "A sign-up screen." },
    when: { ko: "위와 같다 — 톤을 맞출 때.", en: "Same as above — when tone matters." },
  },
  {
    id: "tailark-veil-sign-up-two",
    source: "tailark",
    kind: "sign-up",
    variant: "veil · two",
    what: { ko: "가입 화면.", en: "A sign-up screen." },
    when: { ko: "위와 같다 — 톤을 맞출 때.", en: "Same as above — when tone matters." },
  },
  {
    id: "tailark-veil-stats-four",
    source: "tailark",
    kind: "stats",
    variant: "veil · four",
    what: { ko: "숫자 서너 개로 규모를 보인다.", en: "Three or four numbers showing scale." },
    when: { ko: "실제 숫자가 있을 때만. 없는 숫자를 지어내면 그 페이지 전체의 신뢰가 무너진다.", en: "Only with real numbers. Invented ones cost you the whole page's credibility." },
  },
  {
    id: "tailark-veil-stats-one",
    source: "tailark",
    kind: "stats",
    variant: "veil · one",
    what: { ko: "숫자 서너 개로 규모를 보인다.", en: "Three or four numbers showing scale." },
    when: { ko: "실제 숫자가 있을 때만. 없는 숫자를 지어내면 그 페이지 전체의 신뢰가 무너진다.", en: "Only with real numbers. Invented ones cost you the whole page's credibility." },
  },
  {
    id: "tailark-veil-stats-three",
    source: "tailark",
    kind: "stats",
    variant: "veil · three",
    what: { ko: "숫자 서너 개로 규모를 보인다.", en: "Three or four numbers showing scale." },
    when: { ko: "실제 숫자가 있을 때만. 없는 숫자를 지어내면 그 페이지 전체의 신뢰가 무너진다.", en: "Only with real numbers. Invented ones cost you the whole page's credibility." },
  },
  {
    id: "tailark-veil-stats-two",
    source: "tailark",
    kind: "stats",
    variant: "veil · two",
    what: { ko: "숫자 서너 개로 규모를 보인다.", en: "Three or four numbers showing scale." },
    when: { ko: "실제 숫자가 있을 때만. 없는 숫자를 지어내면 그 페이지 전체의 신뢰가 무너진다.", en: "Only with real numbers. Invented ones cost you the whole page's credibility." },
  },
  {
    id: "tailark-veil-team-one",
    source: "tailark",
    kind: "team",
    variant: "veil · one",
    what: { ko: "만드는 사람들을 보인다.", en: "The people behind it." },
    when: { ko: "사람이 곧 신뢰인 업종 — 에이전시, 컨설팅, 의료.", en: "Where people are the trust — agencies, consulting, care." },
  },
  {
    id: "tailark-veil-team-two",
    source: "tailark",
    kind: "team",
    variant: "veil · two",
    what: { ko: "만드는 사람들을 보인다.", en: "The people behind it." },
    when: { ko: "사람이 곧 신뢰인 업종 — 에이전시, 컨설팅, 의료.", en: "Where people are the trust — agencies, consulting, care." },
  },
  {
    id: "tailark-veil-testimonials-four",
    source: "tailark",
    kind: "testimonials",
    variant: "veil · four",
    what: { ko: "쓴 사람의 말을 인용한다.", en: "Quotes from people who used it." },
    when: { ko: "제품 설명만으로 못 넘는 신뢰의 벽이 있을 때. 실명과 소속이 없으면 효과가 없다.", en: "For the trust gap your own copy can't cross. Without a real name and org, it does nothing." },
  },
  {
    id: "tailark-veil-testimonials-one",
    source: "tailark",
    kind: "testimonials",
    variant: "veil · one",
    what: { ko: "쓴 사람의 말을 인용한다.", en: "Quotes from people who used it." },
    when: { ko: "제품 설명만으로 못 넘는 신뢰의 벽이 있을 때. 실명과 소속이 없으면 효과가 없다.", en: "For the trust gap your own copy can't cross. Without a real name and org, it does nothing." },
  },
  {
    id: "tailark-veil-testimonials-three",
    source: "tailark",
    kind: "testimonials",
    variant: "veil · three",
    what: { ko: "쓴 사람의 말을 인용한다.", en: "Quotes from people who used it." },
    when: { ko: "제품 설명만으로 못 넘는 신뢰의 벽이 있을 때. 실명과 소속이 없으면 효과가 없다.", en: "For the trust gap your own copy can't cross. Without a real name and org, it does nothing." },
  },
  {
    id: "tailark-veil-testimonials-two",
    source: "tailark",
    kind: "testimonials",
    variant: "veil · two",
    what: { ko: "쓴 사람의 말을 인용한다.", en: "Quotes from people who used it." },
    when: { ko: "제품 설명만으로 못 넘는 신뢰의 벽이 있을 때. 실명과 소속이 없으면 효과가 없다.", en: "For the trust gap your own copy can't cross. Without a real name and org, it does nothing." },
  },
]

export const THIRD_PARTY_KINDS = [...new Set(THIRD_PARTY_BLOCKS.map((b) => b.kind))].sort()
