/* 서드파티 블록 카탈로그 — scripts/gen-3p.mjs 가 생성한다. 직접 고치지 말 것.
 *
 * 공식 shadcn 이 다루지 않는 자리를 채운다 — 랜딩 · 마케팅 · 커머스 구획.
 * 종류마다 정의와 선택 조건을 쓰고, 각 항목이 그것을 물려받는다.
 * 전부 MIT 이며 출처는 항목마다 적혀 있다. */
import type { Copy } from "@/components/lang"

export type ThirdPartyBlock = {
  id: string
  source: "tailark" | "launch" | "space"
  kind: string
  variant: string
  what: Copy
  when: Copy
}

export const SOURCES: Record<string, { label: string; url: string; license: string }> = {
  tailark: { label: "Tailark", url: "https://github.com/tailark/blocks", license: "MIT" },
  launch: { label: "Launch UI", url: "https://github.com/launch-ui/launch-ui", license: "MIT" },
  space: { label: "Shadcn Space", url: "https://github.com/shadcnspace/shadcnspace", license: "MIT" },
}

export const THIRD_PARTY_BLOCKS: ThirdPartyBlock[] = [
  {
    id: "launch-faq",
    source: "launch",
    kind: "faq",
    variant: "faq",
    what: { ko: "반복되는 질문을 접어 둔 목록.", en: "Recurring questions, folded away." },
    when: { ko: "지원 문의가 같은 내용으로 계속 올 때.", en: "When support keeps getting the same question." },
  },
  {
    id: "launch-footer",
    source: "launch",
    kind: "footer",
    variant: "footer",
    what: { ko: "페이지 맨 아래의 링크 묶음.", en: "The link block at the bottom." },
    when: { ko: "법적 고지 · 연락처 · 부차 링크가 갈 곳. 여기 있는 것은 아무도 안 찾는다고 가정한다.", en: "Legal, contact, secondary links. Assume nobody goes looking here." },
  },
  {
    id: "launch-navbar",
    source: "launch",
    kind: "navbar",
    variant: "navbar",
    what: { ko: "최상단 전역 탐색.", en: "Global navigation at the top." },
    when: { ko: "링크가 두세 개면 그냥 나열한다. 하위 메뉴가 필요할 만큼 커졌을 때 쓴다.", en: "Two or three links? Just list them. This is for when submenus become necessary." },
  },
  {
    id: "launch-stats",
    source: "launch",
    kind: "stats",
    variant: "stats",
    what: { ko: "숫자 서너 개로 규모를 보인다.", en: "Three or four numbers showing scale." },
    when: { ko: "실제 숫자가 있을 때만. 없는 숫자를 지어내면 그 페이지 전체의 신뢰가 무너진다.", en: "Only with real numbers. Invented ones cost you the whole page's credibility." },
  },
  {
    id: "space-faq-01",
    source: "space",
    kind: "faq",
    variant: "faq-01",
    what: { ko: "반복되는 질문을 접어 둔 목록.", en: "Recurring questions, folded away." },
    when: { ko: "지원 문의가 같은 내용으로 계속 올 때.", en: "When support keeps getting the same question." },
  },
  {
    id: "space-feature-02",
    source: "space",
    kind: "feature",
    variant: "feature-02",
    what: { ko: "제품이 무엇을 하는지 항목으로 나눠 보인다.", en: "What the product does, broken into items." },
    when: { ko: "히어로 바로 아래에 놓는다.", en: "Sits right under the hero." },
  },
  {
    id: "space-footer-01",
    source: "space",
    kind: "footer",
    variant: "footer-01",
    what: { ko: "페이지 맨 아래의 링크 묶음.", en: "The link block at the bottom." },
    when: { ko: "법적 고지 · 연락처 · 부차 링크가 갈 곳. 여기 있는 것은 아무도 안 찾는다고 가정한다.", en: "Legal, contact, secondary links. Assume nobody goes looking here." },
  },
  {
    id: "space-gallery-01",
    source: "space",
    kind: "gallery",
    variant: "gallery-01",
    what: { ko: "이미지 모음.", en: "A set of images." },
    when: { ko: "작업물이 곧 설득 재료인 경우 — 포트폴리오, 제품 사진.", en: "When the work itself is the argument — portfolios, product shots." },
  },
  {
    id: "space-hero-01",
    source: "space",
    kind: "hero",
    variant: "hero-01",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리.", en: "The first thing to settle on a landing page." },
  },
  {
    id: "space-hero-02",
    source: "space",
    kind: "hero",
    variant: "hero-02",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리.", en: "The first thing to settle on a landing page." },
  },
  {
    id: "space-team-01",
    source: "space",
    kind: "team",
    variant: "team-01",
    what: { ko: "만드는 사람들을 보인다.", en: "The people behind it." },
    when: { ko: "사람이 곧 신뢰인 업종 — 에이전시, 컨설팅, 의료.", en: "Where people are the trust — agencies, consulting, care." },
  },
  {
    id: "space-testimonial-01",
    source: "space",
    kind: "testimonial",
    variant: "testimonial-01",
    what: { ko: "쓴 사람의 말을 인용한다.", en: "Quotes from people who used it." },
    when: { ko: "실명과 소속이 없으면 효과가 없다.", en: "Without a real name and org, it does nothing." },
  },
  {
    id: "tailark-dusk-content-four",
    source: "tailark",
    kind: "content",
    variant: "dusk · four",
    what: { ko: "글과 이미지가 섞인 설명 구획.", en: "A prose-and-image section." },
    when: { ko: "히어로에서 다 못한 이야기를 이어갈 때.", en: "For continuing what the hero couldn't finish." },
  },
  {
    id: "tailark-dusk-content-three",
    source: "tailark",
    kind: "content",
    variant: "dusk · three",
    what: { ko: "글과 이미지가 섞인 설명 구획.", en: "A prose-and-image section." },
    when: { ko: "히어로에서 다 못한 이야기를 이어갈 때.", en: "For continuing what the hero couldn't finish." },
  },
  {
    id: "tailark-dusk-content-two",
    source: "tailark",
    kind: "content",
    variant: "dusk · two",
    what: { ko: "글과 이미지가 섞인 설명 구획.", en: "A prose-and-image section." },
    when: { ko: "히어로에서 다 못한 이야기를 이어갈 때.", en: "For continuing what the hero couldn't finish." },
  },
  {
    id: "tailark-dusk-faqs-one",
    source: "tailark",
    kind: "faqs",
    variant: "dusk · one",
    what: { ko: "반복되는 질문을 접어 둔 목록.", en: "Recurring questions, folded away." },
    when: { ko: "지원 문의가 같은 내용으로 계속 올 때. 답이 세 개 미만이면 굳이 접지 않는다.", en: "When support keeps getting the same question. Under three answers, don't fold them." },
  },
  {
    id: "tailark-dusk-features-one",
    source: "tailark",
    kind: "features",
    variant: "dusk · one",
    what: { ko: "제품이 무엇을 하는지 항목으로 나눠 보인다.", en: "What the product does, broken into items." },
    when: { ko: "히어로 바로 아래. 항목마다 '그래서 뭐가 좋은지' 가 없으면 나열에 그친다.", en: "Right under the hero. Without a 'so what' per item, it's just a list." },
  },
  {
    id: "tailark-dusk-footer-one",
    source: "tailark",
    kind: "footer",
    variant: "dusk · one",
    what: { ko: "페이지 맨 아래의 링크 묶음.", en: "The link block at the bottom." },
    when: { ko: "법적 고지 · 연락처 · 부차 링크가 갈 곳. 여기 있는 것은 아무도 안 찾는다고 가정한다.", en: "Legal, contact, secondary links. Assume nobody goes looking here." },
  },
  {
    id: "tailark-dusk-footer-two",
    source: "tailark",
    kind: "footer",
    variant: "dusk · two",
    what: { ko: "페이지 맨 아래의 링크 묶음.", en: "The link block at the bottom." },
    when: { ko: "법적 고지 · 연락처 · 부차 링크가 갈 곳. 여기 있는 것은 아무도 안 찾는다고 가정한다.", en: "Legal, contact, secondary links. Assume nobody goes looking here." },
  },
  {
    id: "tailark-dusk-hero-section-eight",
    source: "tailark",
    kind: "hero-section",
    variant: "dusk · eight",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-dusk-hero-section-five",
    source: "tailark",
    kind: "hero-section",
    variant: "dusk · five",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-dusk-hero-section-four",
    source: "tailark",
    kind: "hero-section",
    variant: "dusk · four",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-dusk-hero-section-nine",
    source: "tailark",
    kind: "hero-section",
    variant: "dusk · nine",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-dusk-hero-section-one",
    source: "tailark",
    kind: "hero-section",
    variant: "dusk · one",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-dusk-hero-section-seven",
    source: "tailark",
    kind: "hero-section",
    variant: "dusk · seven",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-dusk-hero-section-six",
    source: "tailark",
    kind: "hero-section",
    variant: "dusk · six",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-dusk-hero-section-ten",
    source: "tailark",
    kind: "hero-section",
    variant: "dusk · ten",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-dusk-hero-section-three",
    source: "tailark",
    kind: "hero-section",
    variant: "dusk · three",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-dusk-hero-section-two",
    source: "tailark",
    kind: "hero-section",
    variant: "dusk · two",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-dusk-pricing-one",
    source: "tailark",
    kind: "pricing",
    variant: "dusk · one",
    what: { ko: "요금제를 나란히 놓고 고르게 하는 표.", en: "Plans side by side." },
    when: { ko: "안이 3개를 넘으면 비교가 안 된다. 그 이상이면 비교표(comparator)로 바꾼다.", en: "Past three tiers, comparison stops working — switch to a comparator." },
  },
  {
    id: "tailark-dusk-stats-one",
    source: "tailark",
    kind: "stats",
    variant: "dusk · one",
    what: { ko: "숫자 서너 개로 규모를 보인다.", en: "Three or four numbers showing scale." },
    when: { ko: "실제 숫자가 있을 때만. 없는 숫자를 지어내면 그 페이지 전체의 신뢰가 무너진다.", en: "Only with real numbers. Invented ones cost you the whole page's credibility." },
  },
  {
    id: "tailark-dusk-stats-two",
    source: "tailark",
    kind: "stats",
    variant: "dusk · two",
    what: { ko: "숫자 서너 개로 규모를 보인다.", en: "Three or four numbers showing scale." },
    when: { ko: "실제 숫자가 있을 때만. 없는 숫자를 지어내면 그 페이지 전체의 신뢰가 무너진다.", en: "Only with real numbers. Invented ones cost you the whole page's credibility." },
  },
  {
    id: "tailark-dusk-team-two",
    source: "tailark",
    kind: "team",
    variant: "dusk · two",
    what: { ko: "만드는 사람들을 보인다.", en: "The people behind it." },
    when: { ko: "사람이 곧 신뢰인 업종 — 에이전시, 컨설팅, 의료.", en: "Where people are the trust — agencies, consulting, care." },
  },
  {
    id: "tailark-dusk-testimonials-two",
    source: "tailark",
    kind: "testimonials",
    variant: "dusk · two",
    what: { ko: "쓴 사람의 말을 인용한다.", en: "Quotes from people who used it." },
    when: { ko: "제품 설명만으로 못 넘는 신뢰의 벽이 있을 때. 실명과 소속이 없으면 효과가 없다.", en: "For the trust gap your own copy can't cross. Without a real name and org, it does nothing." },
  },
  {
    id: "tailark-mist-faqs-three",
    source: "tailark",
    kind: "faqs",
    variant: "mist · three",
    what: { ko: "반복되는 질문을 접어 둔 목록.", en: "Recurring questions, folded away." },
    when: { ko: "지원 문의가 같은 내용으로 계속 올 때. 답이 세 개 미만이면 굳이 접지 않는다.", en: "When support keeps getting the same question. Under three answers, don't fold them." },
  },
  {
    id: "tailark-mist-features-five",
    source: "tailark",
    kind: "features",
    variant: "mist · five",
    what: { ko: "제품이 무엇을 하는지 항목으로 나눠 보인다.", en: "What the product does, broken into items." },
    when: { ko: "히어로 바로 아래. 항목마다 '그래서 뭐가 좋은지' 가 없으면 나열에 그친다.", en: "Right under the hero. Without a 'so what' per item, it's just a list." },
  },
  {
    id: "tailark-mist-features-seven",
    source: "tailark",
    kind: "features",
    variant: "mist · seven",
    what: { ko: "제품이 무엇을 하는지 항목으로 나눠 보인다.", en: "What the product does, broken into items." },
    when: { ko: "히어로 바로 아래. 항목마다 '그래서 뭐가 좋은지' 가 없으면 나열에 그친다.", en: "Right under the hero. Without a 'so what' per item, it's just a list." },
  },
  {
    id: "tailark-mist-features-ten",
    source: "tailark",
    kind: "features",
    variant: "mist · ten",
    what: { ko: "제품이 무엇을 하는지 항목으로 나눠 보인다.", en: "What the product does, broken into items." },
    when: { ko: "히어로 바로 아래. 항목마다 '그래서 뭐가 좋은지' 가 없으면 나열에 그친다.", en: "Right under the hero. Without a 'so what' per item, it's just a list." },
  },
  {
    id: "tailark-mist-features-two",
    source: "tailark",
    kind: "features",
    variant: "mist · two",
    what: { ko: "제품이 무엇을 하는지 항목으로 나눠 보인다.", en: "What the product does, broken into items." },
    when: { ko: "히어로 바로 아래. 항목마다 '그래서 뭐가 좋은지' 가 없으면 나열에 그친다.", en: "Right under the hero. Without a 'so what' per item, it's just a list." },
  },
  {
    id: "tailark-mist-forgot-password-one",
    source: "tailark",
    kind: "forgot-password",
    variant: "mist · one",
    what: { ko: "비밀번호 재설정 진입.", en: "Password reset entry." },
    when: { ko: "로그인 화면과 짝을 이룬다. 메일이 늦게 올 때의 안내가 필요하다.", en: "Pairs with sign-in. Needs copy for when the mail is slow." },
  },
  {
    id: "tailark-mist-hero-section-one",
    source: "tailark",
    kind: "hero-section",
    variant: "mist · one",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-mist-hero-section-three",
    source: "tailark",
    kind: "hero-section",
    variant: "mist · three",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-mist-hero-section-two",
    source: "tailark",
    kind: "hero-section",
    variant: "mist · two",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-mist-integrations-three",
    source: "tailark",
    kind: "integrations",
    variant: "mist · three",
    what: { ko: "연동되는 서비스의 로고를 늘어놓는다.", en: "Logos of what it connects to." },
    when: { ko: "'이미 쓰는 도구와 붙는다' 가 구매 이유인 제품.", en: "For products where 'it fits your existing stack' is the reason to buy." },
  },
  {
    id: "tailark-mist-login-one",
    source: "tailark",
    kind: "login",
    variant: "mist · one",
    what: { ko: "로그인 화면.", en: "A sign-in screen." },
    when: { ko: "공식 블록에도 5종이 있다. 이쪽은 마케팅 페이지와 톤을 맞추고 싶을 때.", en: "The official set has five. Use these when the tone must match the marketing site." },
  },
  {
    id: "tailark-mist-sign-up-one",
    source: "tailark",
    kind: "sign-up",
    variant: "mist · one",
    what: { ko: "가입 화면.", en: "A sign-up screen." },
    when: { ko: "위와 같다 — 톤을 맞출 때.", en: "Same as above — when tone matters." },
  },
  {
    id: "tailark-mist-testimonials-five",
    source: "tailark",
    kind: "testimonials",
    variant: "mist · five",
    what: { ko: "쓴 사람의 말을 인용한다.", en: "Quotes from people who used it." },
    when: { ko: "제품 설명만으로 못 넘는 신뢰의 벽이 있을 때. 실명과 소속이 없으면 효과가 없다.", en: "For the trust gap your own copy can't cross. Without a real name and org, it does nothing." },
  },
  {
    id: "tailark-veil-forgot-password-three",
    source: "tailark",
    kind: "forgot-password",
    variant: "veil · three",
    what: { ko: "비밀번호 재설정 진입.", en: "Password reset entry." },
    when: { ko: "로그인 화면과 짝을 이룬다. 메일이 늦게 올 때의 안내가 필요하다.", en: "Pairs with sign-in. Needs copy for when the mail is slow." },
  },
  {
    id: "tailark-veil-hero-section-five",
    source: "tailark",
    kind: "hero-section",
    variant: "veil · five",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-veil-hero-section-four",
    source: "tailark",
    kind: "hero-section",
    variant: "veil · four",
    what: { ko: "첫 화면 최상단. 무엇을 하는 제품인지 한 문장과 다음 행동 하나.", en: "The top of a landing page — one sentence on what this is, and one next action." },
    when: { ko: "랜딩 페이지를 만들 때 가장 먼저 정하는 자리. 문장이 없으면 어떤 히어로를 골라도 안 읽힌다.", en: "The first thing to settle on a landing page. Without the sentence, no hero design saves it." },
  },
  {
    id: "tailark-veil-login-one",
    source: "tailark",
    kind: "login",
    variant: "veil · one",
    what: { ko: "로그인 화면.", en: "A sign-in screen." },
    when: { ko: "공식 블록에도 5종이 있다. 이쪽은 마케팅 페이지와 톤을 맞추고 싶을 때.", en: "The official set has five. Use these when the tone must match the marketing site." },
  },
  {
    id: "tailark-veil-login-three",
    source: "tailark",
    kind: "login",
    variant: "veil · three",
    what: { ko: "로그인 화면.", en: "A sign-in screen." },
    when: { ko: "공식 블록에도 5종이 있다. 이쪽은 마케팅 페이지와 톤을 맞추고 싶을 때.", en: "The official set has five. Use these when the tone must match the marketing site." },
  },
  {
    id: "tailark-veil-login-two",
    source: "tailark",
    kind: "login",
    variant: "veil · two",
    what: { ko: "로그인 화면.", en: "A sign-in screen." },
    when: { ko: "공식 블록에도 5종이 있다. 이쪽은 마케팅 페이지와 톤을 맞추고 싶을 때.", en: "The official set has five. Use these when the tone must match the marketing site." },
  },
  {
    id: "tailark-veil-sign-up-one",
    source: "tailark",
    kind: "sign-up",
    variant: "veil · one",
    what: { ko: "가입 화면.", en: "A sign-up screen." },
    when: { ko: "위와 같다 — 톤을 맞출 때.", en: "Same as above — when tone matters." },
  },
  {
    id: "tailark-veil-sign-up-three",
    source: "tailark",
    kind: "sign-up",
    variant: "veil · three",
    what: { ko: "가입 화면.", en: "A sign-up screen." },
    when: { ko: "위와 같다 — 톤을 맞출 때.", en: "Same as above — when tone matters." },
  },
  {
    id: "tailark-veil-stats-four",
    source: "tailark",
    kind: "stats",
    variant: "veil · four",
    what: { ko: "숫자 서너 개로 규모를 보인다.", en: "Three or four numbers showing scale." },
    when: { ko: "실제 숫자가 있을 때만. 없는 숫자를 지어내면 그 페이지 전체의 신뢰가 무너진다.", en: "Only with real numbers. Invented ones cost you the whole page's credibility." },
  },
]

export const THIRD_PARTY_KINDS = [...new Set(THIRD_PARTY_BLOCKS.map((b) => b.kind))].sort()
