/* scripts/gen-3p.mjs 가 생성한다. 직접 고치지 말 것.
 * 서드파티 블록 56개를 id 로 찾을 수 있게 모아 둔 지도.
 * next/dynamic 으로 나눠 담아, 목록 라우트가 185개를 한 번에 끌고 오지 않게 한다. */
import dynamic from "next/dynamic"
import type { ComponentType } from "react"

export const THIRD_PARTY: Record<string, ComponentType> = {
  "launch-faq": dynamic(() => import("@/components/3p/launch/faq/default")),
  "launch-footer": dynamic(() => import("@/components/3p/launch/footer/default")),
  "launch-navbar": dynamic(() => import("@/components/3p/launch/navbar/default")),
  "launch-stats": dynamic(() => import("@/components/3p/launch/stats/default")),
  "space-faq-01": dynamic(() => import("@/components/3p/space/faq-01/faq")),
  "space-feature-02": dynamic(() => import("@/components/3p/space/feature-02/index")),
  "space-footer-01": dynamic(() => import("@/components/3p/space/footer-01/footer")),
  "space-gallery-01": dynamic(() => import("@/components/3p/space/gallery-01/gallery")),
  "space-hero-01": dynamic(() => import("@/components/3p/space/hero-01/index")),
  "space-hero-02": dynamic(() => import("@/components/3p/space/hero-02/index")),
  "space-team-01": dynamic(() => import("@/components/3p/space/team-01/page")),
  "space-testimonial-01": dynamic(() => import("@/components/3p/space/testimonial-01/page")),
  "tailark-dusk-content-four": dynamic(() => import("@/components/3p/tailark/dusk-content-four")),
  "tailark-dusk-content-three": dynamic(() => import("@/components/3p/tailark/dusk-content-three")),
  "tailark-dusk-content-two": dynamic(() => import("@/components/3p/tailark/dusk-content-two")),
  "tailark-dusk-faqs-one": dynamic(() => import("@/components/3p/tailark/dusk-faqs-one")),
  "tailark-dusk-features-one": dynamic(() => import("@/components/3p/tailark/dusk-features-one")),
  "tailark-dusk-footer-one": dynamic(() => import("@/components/3p/tailark/dusk-footer-one")),
  "tailark-dusk-footer-two": dynamic(() => import("@/components/3p/tailark/dusk-footer-two")),
  "tailark-dusk-hero-section-eight": dynamic(() => import("@/components/3p/tailark/dusk-hero-section-eight")),
  "tailark-dusk-hero-section-five": dynamic(() => import("@/components/3p/tailark/dusk-hero-section-five")),
  "tailark-dusk-hero-section-four": dynamic(() => import("@/components/3p/tailark/dusk-hero-section-four")),
  "tailark-dusk-hero-section-nine": dynamic(() => import("@/components/3p/tailark/dusk-hero-section-nine")),
  "tailark-dusk-hero-section-one": dynamic(() => import("@/components/3p/tailark/dusk-hero-section-one")),
  "tailark-dusk-hero-section-seven": dynamic(() => import("@/components/3p/tailark/dusk-hero-section-seven")),
  "tailark-dusk-hero-section-six": dynamic(() => import("@/components/3p/tailark/dusk-hero-section-six")),
  "tailark-dusk-hero-section-ten": dynamic(() => import("@/components/3p/tailark/dusk-hero-section-ten")),
  "tailark-dusk-hero-section-three": dynamic(() => import("@/components/3p/tailark/dusk-hero-section-three")),
  "tailark-dusk-hero-section-two": dynamic(() => import("@/components/3p/tailark/dusk-hero-section-two")),
  "tailark-dusk-pricing-one": dynamic(() => import("@/components/3p/tailark/dusk-pricing-one")),
  "tailark-dusk-stats-one": dynamic(() => import("@/components/3p/tailark/dusk-stats-one")),
  "tailark-dusk-stats-two": dynamic(() => import("@/components/3p/tailark/dusk-stats-two")),
  "tailark-dusk-team-two": dynamic(() => import("@/components/3p/tailark/dusk-team-two")),
  "tailark-dusk-testimonials-two": dynamic(() => import("@/components/3p/tailark/dusk-testimonials-two")),
  "tailark-mist-faqs-three": dynamic(() => import("@/components/3p/tailark/mist-faqs-three")),
  "tailark-mist-features-five": dynamic(() => import("@/components/3p/tailark/mist-features-five")),
  "tailark-mist-features-seven": dynamic(() => import("@/components/3p/tailark/mist-features-seven")),
  "tailark-mist-features-ten": dynamic(() => import("@/components/3p/tailark/mist-features-ten")),
  "tailark-mist-features-two": dynamic(() => import("@/components/3p/tailark/mist-features-two")),
  "tailark-mist-forgot-password-one": dynamic(() => import("@/components/3p/tailark/mist-forgot-password-one")),
  "tailark-mist-hero-section-one": dynamic(() => import("@/components/3p/tailark/mist-hero-section-one")),
  "tailark-mist-hero-section-three": dynamic(() => import("@/components/3p/tailark/mist-hero-section-three")),
  "tailark-mist-hero-section-two": dynamic(() => import("@/components/3p/tailark/mist-hero-section-two")),
  "tailark-mist-integrations-three": dynamic(() => import("@/components/3p/tailark/mist-integrations-three")),
  "tailark-mist-login-one": dynamic(() => import("@/components/3p/tailark/mist-login-one")),
  "tailark-mist-sign-up-one": dynamic(() => import("@/components/3p/tailark/mist-sign-up-one")),
  "tailark-mist-testimonials-five": dynamic(() => import("@/components/3p/tailark/mist-testimonials-five")),
  "tailark-veil-forgot-password-three": dynamic(() => import("@/components/3p/tailark/veil-forgot-password-three")),
  "tailark-veil-hero-section-five": dynamic(() => import("@/components/3p/tailark/veil-hero-section-five")),
  "tailark-veil-hero-section-four": dynamic(() => import("@/components/3p/tailark/veil-hero-section-four")),
  "tailark-veil-login-one": dynamic(() => import("@/components/3p/tailark/veil-login-one")),
  "tailark-veil-login-three": dynamic(() => import("@/components/3p/tailark/veil-login-three")),
  "tailark-veil-login-two": dynamic(() => import("@/components/3p/tailark/veil-login-two")),
  "tailark-veil-sign-up-one": dynamic(() => import("@/components/3p/tailark/veil-sign-up-one")),
  "tailark-veil-sign-up-three": dynamic(() => import("@/components/3p/tailark/veil-sign-up-three")),
  "tailark-veil-stats-four": dynamic(() => import("@/components/3p/tailark/veil-stats-four")),
}

export const THIRD_PARTY_IDS = Object.keys(THIRD_PARTY)
